web_analysis_task:
  description: >
    Analyze the web search results and extract relevant information about {question}.
    Summarize the key points and insights from the web search results.
    
    INSTRUCTIONS:
    - Use the web search tool to find information about: {question}
    - Analyze all search results carefully
    - Extract only relevant and accurate information
    - Focus on culinary/cooking related content
    - If no relevant results found, clearly state this
    - Provide a structured summary with key points
  expected_output: >
    A structured summary containing:
    1. Key findings from web search about {question}
    2. Relevant culinary information extracted
    3. Sources and references found
    4. Any gaps in information that were identified
    
    Format the output as a clear, organized summary that directly addresses {question}.
  agent: web_analyst